// ---------------------------------------------------------------------------
// PDF generation.
//
// Generates a completed PDF from a submission + its form definition. Because
// the PDF is rendered from the schema + data, changing a form NEVER means
// editing a Word doc and re-exporting a PDF. The document follows the form.
// ---------------------------------------------------------------------------
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

const BLUE = rgb(0.055, 0.11, 0.259); // #0E1C42
const BIT = rgb(0.333, 0.784, 0.91); // #55C8E8
const GREY = rgb(0.42, 0.45, 0.5);
const LINE = rgb(0.89, 0.91, 0.94);

function pretty(value) {
  if (value === true) return 'Yes';
  if (value === false) return 'No';
  if (Array.isArray(value)) return value.join(', ');
  if (value === null || value === undefined || value === '') return '—';
  return String(value);
}

export async function generateSubmissionPdf({ definition, submission, candidate, signatures }) {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page = pdf.addPage([612, 792]); // US Letter
  const M = 54;
  const W = 612 - M * 2;
  let y = 792 - M;

  const ensureSpace = (need) => {
    if (y - need < M) {
      page = pdf.addPage([612, 792]);
      y = 792 - M;
    }
  };

  // Header band
  page.drawRectangle({ x: 0, y: 792 - 8, width: 612, height: 8, color: BIT });
  page.drawText('OPTIMA', { x: M, y, size: 20, font: bold, color: BLUE });
  page.drawText('Education Experience Company', { x: M + 86, y: y + 3, size: 8, font, color: GREY });
  y -= 30;
  page.drawText(definition.title, { x: M, y, size: 16, font: bold, color: BLUE });
  y -= 16;
  if (candidate) {
    page.drawText(`${candidate.firstName} ${candidate.lastName}  ·  ${candidate.position || ''}`,
      { x: M, y, size: 10, font, color: GREY });
    y -= 14;
  }
  page.drawText(`Submitted ${new Date(submission.submittedAt || Date.now()).toLocaleString('en-US')}`,
    { x: M, y, size: 8, font, color: GREY });
  y -= 10;
  page.drawLine({ start: { x: M, y }, end: { x: M + W, y }, thickness: 1, color: LINE });
  y -= 24;

  // Fields
  for (const f of definition.fields) {
    if (f.type === 'section') {
      ensureSpace(36);
      page.drawText(String(f.label).toUpperCase(), { x: M, y, size: 9, font: bold, color: BIT });
      y -= 18;
      continue;
    }
    const valRaw = submission.data?.[f.key];
    const val = f.type === 'attestation'
      ? (valRaw ? 'Acknowledged & accepted' : 'Not accepted')
      : pretty(valRaw);

    // wrap value text
    const maxChars = 70;
    const words = val.split(' ');
    const lines = [];
    let cur = '';
    for (const w of words) {
      if ((cur + ' ' + w).trim().length > maxChars) { lines.push(cur.trim()); cur = w; }
      else cur += ' ' + w;
    }
    if (cur.trim()) lines.push(cur.trim());
    if (lines.length === 0) lines.push('—');

    ensureSpace(16 + lines.length * 13);
    page.drawText(f.label, { x: M, y, size: 8, font: bold, color: GREY });
    y -= 13;
    for (const ln of lines) {
      page.drawText(ln, { x: M, y, size: 11, font, color: BLUE });
      y -= 13;
    }
    y -= 6;
  }

  // Signature chain (RTH)
  if (signatures && signatures.length) {
    ensureSpace(40);
    y -= 6;
    page.drawLine({ start: { x: M, y }, end: { x: M + W, y }, thickness: 1, color: LINE });
    y -= 18;
    page.drawText('SIGNATURE CHAIN', { x: M, y, size: 9, font: bold, color: BIT });
    y -= 18;
    for (const s of signatures) {
      ensureSpace(16);
      const status = s.signedAt
        ? `Signed by ${s.signedBy} on ${new Date(s.signedAt).toLocaleString('en-US')}`
        : 'Pending';
      page.drawText(`${s.label} (${s.role})`, { x: M, y, size: 10, font: bold, color: BLUE });
      page.drawText(status, { x: M + 200, y, size: 9, font, color: s.signedAt ? rgb(0.2, 0.55, 0.2) : GREY });
      y -= 16;
    }
  }

  // Footer
  page.drawText('Generated by the Optima Onboarding system — completed record of submission.',
    { x: M, y: M - 18, size: 7, font, color: GREY });

  return await pdf.save();
}
